### ISSUE TITLE
License of "ptoc" .

### ISSUE THREAD

**Issue by sanliturk** [knizhnik/ptoc#1]
In the "ptoc" repository :

https://github.com/knizhnik/ptoc

there is no an explicit "License" file .

In 

http://www.garret.ru/

there is a page 

http://www.garret.ru/license.html

which seems to be valid over the web site as a whole .

In the pages

http://www.garret.ru/ptoc/Readme.htm

and 

https://github.com/knizhnik/ptoc   ( displayed Readme.htm )

and

https://github.com/knizhnik/ptoc/blob/master/Readme.htm

at the end of the page , there are the following paragraph :

"
PtoC is shareware and is distributed in the hope to be useful. 
Your are free to use this converter, modify the sources 
and do with this converter everything else you want. 
Also feel free to ask me any questions about the converter
and BGI emulator for Windows. Shareware status doesn't mean 
lack of support. I will do my best to fix all reported bugs
and will help you to tune PtoC to fit your requirements.
Also e-mail support is guaranteed.
"

In previous , old times , "shareware" concept was different from
the license specified in

http://www.garret.ru/license.html

where a detailed explanation of existent "shareware" concept may be found
in the following page :

https://en.wikipedia.org/wiki/Shareware

Since a local ( inner ) license condition overrides an outer license 
condition , the "License" specified in the page

http://www.garret.ru/license.html

can not be assumed valid for "ptoc" .

A resolution would be any one of the following :

(1) 

Specify explicitly conditions of "shareware" which requires "payment" 
requirements and how to pay decided amount and/or fulfilling the other
conditions ,

(2)

Remove the above specified "shareware" paragraph from the

.../Readme.htm

and mention explicitly a stored license file name .

"ptoc" is a very nice program and it is distributed as a package by many operating system
producers .

With respect to existent laws in many countries , and some religion  beliefs ,
any action contrary to your specification is a violation of your rights ,

Thank you very much .

Mehmet Erol Sanliturk

**Comment by sanliturk** [comment]
It seems that this issue is not necessary .

**Comment by asiekierka** [comment]
It would still be good to clarify the license of "ptoc", especially as "ptoc"-converted software requires the inclusion of some code from "ptoc" (ptoc.h, paslib.h, etc.)

**Comment by knizhnik** [comment]
Sorry, PtoC, as well as most of my other free projects, is distributed under MIT license.

**Comment by sanliturk** [comment]
Dear Konstantin ,

Thank you very much for reply .

I had opened the issue about need for license clarification .
When I could not get a reply I had thought that you archived the sources as they were .
Then I had closed the issue .

Clarification of license of PtoC is a very good contribution to all of its users ,
because PtoC is a very good software .


In the Readme.htm , if you modify "shareware" in the following sentence to supply a donation account ,
it may remove license restriction and allows users to make contributions to your works :

" 
PtoC is shareware and is distributed in the hope to be useful. 
"

and 

include  "MIT" into the repository license field .

With my best wishes for you , your family and all .

Mehmet Erol Sanliturk
